export const SET_FOLDERS = 'SET_FOLDERS';
export const CREATE_FOLDER = 'CREATE_FOLDER';
export const UPDATE_FOLDER = 'MANAGE_FOLDER';
export const REMOVE_FOLDER = 'REMOVE_FOLDER';

export const SET_BOOKMARKS = 'SET_BOOKMARKS';
export const CREATE_BOOKMARK = 'CREATE_BOOKMARK';
export const UPDATE_BOOKMARK = 'UPDATE_BOOKMARK';
export const REMOVE_BOOKMARK = 'REMOVE_BOOKMARK';